usuario_usuario:
    resource: "@UsuarioBundle/Resources/config/routing/usuario.yml"
    prefix:   /usuario

usuarios:
    resource: "@UsuarioBundle/Resources/config/routing/usuarios.yml"
    prefix:   /usuarios

