<?php

namespace Software\TicketBundle\Entity;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
	/*public function misticket($id)
	{
		return $this->getEntityManager()->createQuery('SELECT t FROM TicketBundle:Ticket t WHERE t.usuarioCreo = :id')->setParameter('id', $id)->getResult();
	}*/

	public function nuevoTicket($id)
    {
     	$query = $this->getEntityManager()->createQuery('SELECT t FROM TicketBundle:Ticket t, UsuarioBundle:Usuario u  INNER JOIN u.proyecto p WHERE t.proyecto = p.id  AND u.id = :id AND t.aplica = \'f\' AND t.resuelto = \'f\' ORDER BY t.id DESC')->setParameter('id',$id)->getResult();
  		return $query;
    }

    public function noAplica($id)
    {
     	$query = $this->getEntityManager()->createQuery('SELECT t FROM TicketBundle:Ticket t, UsuarioBundle:Usuario u  INNER JOIN u.proyecto p WHERE t.proyecto = p.id  AND u.id = :id AND t.aplica = \'t\' ORDER BY t.id DESC')->setParameter('id',$id)->getResult();
  		return $query;
    } 

    public function resuelto($id)
    {
     	$query = $this->getEntityManager()->createQuery('SELECT t FROM TicketBundle:Ticket t, UsuarioBundle:Usuario u  INNER JOIN u.proyecto p WHERE t.proyecto = p.id  AND u.id = :id AND t.resuelto = \'t\' ORDER BY t.id DESC')->setParameter('id',$id)->getResult();
  		return $query;
    }

	public function creados($id)
	{
		return $this->getEntityManager()->createQuery('SELECT t FROM TicketBundle:Ticket t WHERE t.usuarioCreo = :id')->setParameter('id',$id)->getResult();
	}

  public function todosTicket($id)
  {
    return $this->getEntityManager()->createQuery('SELECT t AS ticket, u.userName AS usuario FROM TicketBundle:Ticket t, UsuarioBundle:Usuario u WHERE t.usuarioCreo = u.id AND t.id = :id')->setParameter('id',$id)->getResult();
  }
}
