<?php

namespace Software\TicketBundle\Entity;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
	/*public function misticket($id)
	{
		return $this->getEntityManager()->createQuery('SELECT t FROM TicketBundle:Ticket t WHERE t.usuarioCreo = :id')->setParameter('id', $id)->getResult();
	}*/

	public function misticket($id)
	{
		return $this->getEntityManager()->createQuery('SELECT t FROM TicketBundle:Ticket t LEFT JOIN t.proyecto p INNER JOIN p.usuario u WHERE p.id = :id')->setParameter('id',$id)->getResult();
	}

	public function creados($id)
	{
		return $this->getEntityManager()->createQuery('SELECT t FROM TicketBundle:Ticket t WHERE t.usuarioCreo = :id')->setParameter('id',$id)->getResult();
	}
}
