imagen:
    path:     /
    defaults: { _controller: "TicketBundle:Imagen:index" }

imagen_show:
    path:     /{id}/show
    defaults: { _controller: "TicketBundle:Imagen:show" }

imagen_new:
    path:     /new
    defaults: { _controller: "TicketBundle:Imagen:new" }

imagen_create:
    path:     /create
    defaults: { _controller: "TicketBundle:Imagen:create" }
    methods:  POST

imagen_edit:
    path:     /{id}/edit
    defaults: { _controller: "TicketBundle:Imagen:edit" }

imagen_update:
    path:     /{id}/update
    defaults: { _controller: "TicketBundle:Imagen:update" }
    methods:  [POST, PUT]

imagen_delete:
    path:     /{id}/delete
    defaults: { _controller: "TicketBundle:Imagen:delete" }
    methods:  [POST, DELETE]
